# Generated by Django 4.1.5 on 2023-01-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VInformacionCitas",
            fields=[
                ("id_hd", models.AutoField(primary_key=True, serialize=False)),
                ("no_cita", models.CharField(max_length=25)),
                ("no_orden", models.CharField(max_length=25)),
                ("cliente", models.CharField(blank=True, max_length=200, null=True)),
                ("hora_llegada", models.DateTimeField(blank=True, null=True)),
                ("hora_retiro", models.DateTimeField(blank=True, null=True)),
                ("placas", models.CharField(blank=True, max_length=10, null=True)),
                ("vin", models.CharField(blank=True, max_length=50, null=True)),
                ("vehiculo", models.CharField(blank=True, max_length=250, null=True)),
                ("color", models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                "db_table": "v_informacion_citas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VInformacionHistorica",
            fields=[
                ("id_hd", models.AutoField(primary_key=True, serialize=False)),
                ("numcita", models.CharField(db_column="NUMCITA", max_length=25)),
                ("noorden", models.CharField(db_column="NOORDEN", max_length=25)),
                ("fecha", models.DateTimeField()),
                (
                    "horaasesor",
                    models.DateTimeField(blank=True, db_column="horaAsesor", null=True),
                ),
                ("idasesor", models.CharField(max_length=10)),
                (
                    "noplacas",
                    models.CharField(
                        blank=True, db_column="noPlacas", max_length=50, null=True
                    ),
                ),
                ("vin", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "colorprisma",
                    models.CharField(
                        blank=True, db_column="colorPrisma", max_length=25, null=True
                    ),
                ),
                (
                    "vehiculo",
                    models.CharField(
                        blank=True, db_column="Vehiculo", max_length=250, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, db_column="Color", max_length=25, null=True
                    ),
                ),
                ("ano", models.IntegerField(blank=True, db_column="Ano", null=True)),
                (
                    "cilindros",
                    models.IntegerField(blank=True, db_column="Cilindros", null=True),
                ),
                (
                    "kilometraje",
                    models.IntegerField(blank=True, db_column="Kilometraje", null=True),
                ),
                (
                    "idcliente",
                    models.CharField(
                        blank=True, db_column="idCliente", max_length=10, null=True
                    ),
                ),
                (
                    "cliente",
                    models.CharField(
                        blank=True, db_column="Cliente", max_length=200, null=True
                    ),
                ),
                (
                    "tipocliente",
                    models.CharField(
                        blank=True, db_column="tipoCliente", max_length=25, null=True
                    ),
                ),
                ("telefonos", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contactonombre",
                    models.CharField(
                        blank=True,
                        db_column="ContactoNombre",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "contactotelefono",
                    models.CharField(
                        blank=True,
                        db_column="ContactoTelefono",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "horatolerancia",
                    models.DateTimeField(
                        blank=True, db_column="horaTolerancia", null=True
                    ),
                ),
                (
                    "horallegada",
                    models.DateTimeField(
                        blank=True, db_column="Horallegada", null=True
                    ),
                ),
                (
                    "horairecepcion",
                    models.DateTimeField(
                        blank=True, db_column="HoraIRecepcion", null=True
                    ),
                ),
                (
                    "horafrecepcion",
                    models.DateTimeField(
                        blank=True, db_column="HoraFRecepcion", null=True
                    ),
                ),
                (
                    "horaientrega",
                    models.DateTimeField(
                        blank=True, db_column="HoraIEntrega", null=True
                    ),
                ),
                (
                    "horafentrega",
                    models.DateTimeField(
                        blank=True, db_column="HoraFEntrega", null=True
                    ),
                ),
                (
                    "horaretiro",
                    models.DateTimeField(blank=True, db_column="HoraRetiro", null=True),
                ),
                (
                    "horarampa",
                    models.DateTimeField(blank=True, db_column="horaRampa", null=True),
                ),
                (
                    "fechahorapromesa",
                    models.DateTimeField(
                        blank=True, db_column="fechaHoraPromesa", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, db_column="Status", max_length=30, null=True
                    ),
                ),
                (
                    "fecha_hora_status",
                    models.DateTimeField(
                        blank=True, db_column="Fecha_hora_Status", null=True
                    ),
                ),
                (
                    "idop",
                    models.DecimalField(
                        db_column="idOp", decimal_places=0, max_digits=18
                    ),
                ),
                ("bahia", models.IntegerField(blank=True, null=True)),
                (
                    "observaciones",
                    models.CharField(
                        blank=True, db_column="OBSERVACIONES", max_length=250, null=True
                    ),
                ),
                (
                    "usuario",
                    models.CharField(
                        blank=True, db_column="USUARIO", max_length=50, null=True
                    ),
                ),
                (
                    "fecha_agendado",
                    models.DateTimeField(
                        blank=True, db_column="FECHA_AGENDADO", null=True
                    ),
                ),
                (
                    "fecha_original",
                    models.DateTimeField(
                        blank=True, db_column="FECHA_ORIGINAL", null=True
                    ),
                ),
                ("fecha_hora_apertura_os", models.DateTimeField(blank=True, null=True)),
                ("fecha_hora_cierre_os", models.DateTimeField(blank=True, null=True)),
                (
                    "fecha_hora_com",
                    models.DateTimeField(
                        blank=True, db_column="Fecha_hora_com", null=True
                    ),
                ),
                (
                    "status_os",
                    models.CharField(
                        blank=True, db_column="Status_OS", max_length=15, null=True
                    ),
                ),
                ("seriecolorprisma", models.IntegerField(blank=True, null=True)),
                (
                    "testqa",
                    models.DateTimeField(blank=True, db_column="testQA", null=True),
                ),
                ("tipolavado", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "comentarioslavado",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "tipollegada",
                    models.CharField(
                        blank=True, db_column="tipoLlegada", max_length=5, null=True
                    ),
                ),
                (
                    "tiporetiro",
                    models.CharField(
                        blank=True, db_column="tipoRetiro", max_length=5, null=True
                    ),
                ),
            ],
            options={
                "db_table": "v_informacion_historica",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VTracker",
            fields=[
                (
                    "no_orden",
                    models.CharField(
                        blank=True, max_length=25, primary_key=True, serialize=False
                    ),
                ),
                ("placas", models.CharField(blank=True, max_length=10, null=True)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("tecnico", models.CharField(blank=True, max_length=60, null=True)),
                ("asesor", models.CharField(blank=True, max_length=150, null=True)),
                ("vehiculo", models.CharField(blank=True, max_length=250, null=True)),
                ("hora_llegada", models.DateTimeField(blank=True, null=True)),
                ("hora_inicio_asesor", models.DateTimeField(blank=True, null=True)),
                ("hora_fin_asesor", models.DateTimeField(blank=True, null=True)),
                ("hora_promesa", models.DateTimeField(blank=True, null=True)),
                ("hora_grabado", models.CharField(blank=True, max_length=5, null=True)),
                ("inicio_tecnico", models.DateTimeField(blank=True, null=True)),
                ("fin_tecnico", models.DateTimeField(blank=True, null=True)),
                ("detenido", models.CharField(max_length=5)),
                (
                    "servicio_capturado",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("inicio_tecnico_lavado", models.DateTimeField(blank=True, null=True)),
                ("fin_tecnico_lavado", models.DateTimeField(blank=True, null=True)),
                ("ultima_actualizacion", models.IntegerField(blank=True, null=True)),
                ("motivo_paro", models.CharField(blank=True, max_length=22, null=True)),
                ("id_hd", models.CharField(max_length=25)),
                ("telefono_agencia", models.CharField(max_length=25)),
            ],
            options={
                "verbose_name": "Ordenes con tracker",
                "verbose_name_plural": "Ordenes con tracker",
                "db_table": "v_tracker",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ActividadesPrediagnostico",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("no_cita", models.CharField(blank=True, max_length=100, null=True)),
                ("nombre", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "comentarios",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("evidencia", models.CharField(blank=True, max_length=400, null=True)),
                ("existencia", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "actividades_prediagnostico",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ActividadesPreinventario",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("no_cita", models.CharField(blank=True, max_length=100, null=True)),
                ("nombre", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "comentarios",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("evidencia", models.CharField(blank=True, max_length=400, null=True)),
                ("existencia", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "actividades_preinventario",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ListaItemsFamiliasPrediagnostico",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=50, null=True)),
                ("descripcion", models.CharField(blank=True, max_length=50, null=True)),
                ("orden", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "familia de items de pre-diagnostico",
                "verbose_name_plural": "Familias de items de pre-diagnostico",
                "db_table": "lista_items_familias_prediagnostico",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ListaItemsFamiliasPreinventario",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("orden", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "familia de items de pre-inventario",
                "verbose_name_plural": "Familias de items de pre-inventario",
                "db_table": "lista_items_familias_preinventario",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ListaItemsPrediagnostico",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("familia", models.CharField(blank=True, max_length=50, null=True)),
                ("orden", models.BigIntegerField(blank=True, null=True)),
                ("comentarios", models.BooleanField(blank=True, null=True)),
                ("evidencia", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "item de pre-diagnostico",
                "verbose_name_plural": "Items de pre-diagnostico",
                "db_table": "lista_items_prediagnostico",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ListaItemsPreinventario",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("familia", models.CharField(blank=True, max_length=50, null=True)),
                ("orden", models.BigIntegerField(blank=True, null=True)),
                ("comentarios", models.BooleanField(blank=True, null=True)),
                ("evidencia", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "item de pre-inventario",
                "verbose_name_plural": "Items de pre-inventario",
                "db_table": "lista_items_preinventario",
                "managed": True,
            },
        ),
    ]
