# Generated by Django 4.0.3 on 2022-03-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VCitasTecnicos',
            fields=[
                ('id_empleado', models.CharField(db_column='ID_EMPLEADO', max_length=10, primary_key=True, serialize=False)),
                ('id_tipo_empleado', models.CharField(blank=True, db_column='ID_TIPO_EMPLEADO', max_length=10, null=True)),
                ('nombre_empleado', models.CharField(blank=True, db_column='NOMBRE_EMPLEADO', max_length=60, null=True)),
                ('nivel', models.CharField(blank=True, db_column='NIVEL', max_length=1, null=True)),
                ('bahia', models.IntegerField(blank=True, db_column='BAHIA', null=True)),
                ('express', models.BooleanField(blank=True, db_column='EXPRESS', null=True)),
                ('color_tecnico', models.CharField(blank=True, db_column='COLOR_TECNICO', max_length=25, null=True)),
                ('hora_ent_lv', models.CharField(blank=True, db_column='HORA_ENT_LV', max_length=5, null=True)),
                ('hora_sal_lv', models.CharField(blank=True, db_column='HORA_SAL_LV', max_length=5, null=True)),
                ('hora_comer', models.CharField(blank=True, db_column='HORA_COMER', max_length=5, null=True)),
                ('hora_ent_s', models.CharField(blank=True, db_column='HORA_ENT_S', max_length=5, null=True)),
                ('hora_sal_s', models.CharField(blank=True, db_column='HORA_SAL_S', max_length=5, null=True)),
                ('id_asesor', models.CharField(blank=True, db_column='ID_ASESOR', max_length=10, null=True)),
                ('nombre_asesor', models.CharField(blank=True, db_column='NOMBRE_ASESOR', max_length=50, null=True)),
                ('no_emp_asesor', models.IntegerField(blank=True, db_column='NO_EMP_ASESOR', null=True)),
                ('jefe_taller', models.BooleanField(blank=True, db_column='JEFE_TALLER', null=True)),
                ('hora_ent_d', models.CharField(blank=True, db_column='HORA_ENT_D', max_length=5, null=True)),
                ('hora_sal_d', models.CharField(blank=True, db_column='HORA_SAL_D', max_length=5, null=True)),
                ('hora_comer_s', models.CharField(blank=True, db_column='HORA_COMER_S', max_length=5, null=True)),
                ('hora_comer_d', models.CharField(blank=True, db_column='HORA_COMER_D', max_length=5, null=True)),
                ('id_empleado_bi', models.CharField(blank=True, db_column='ID_EMPLEADO_BI', max_length=10, null=True)),
                ('min_comer_lv', models.IntegerField(blank=True, db_column='MIN_COMER_LV', null=True)),
                ('min_comer_s', models.IntegerField(blank=True, db_column='MIN_COMER_S', null=True)),
                ('min_comer_d', models.IntegerField(blank=True, db_column='MIN_COMER_D', null=True)),
            ],
            options={
                'db_table': 'tecnicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VCitasTracker',
            fields=[
                ('no_orden', models.CharField(blank=True, max_length=25, primary_key=True, serialize=False)),
                ('placas', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tecnico', models.CharField(blank=True, max_length=60, null=True)),
                ('asesor', models.CharField(blank=True, max_length=150, null=True)),
                ('vehiculo', models.CharField(blank=True, max_length=250, null=True)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio_asesor', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_asesor', models.DateTimeField(blank=True, null=True)),
                ('hora_promesa', models.DateTimeField(blank=True, null=True)),
                ('hora_grabado', models.CharField(blank=True, max_length=5, null=True)),
                ('inicio_tecnico', models.DateTimeField(blank=True, null=True)),
                ('fin_tecnico', models.DateTimeField(blank=True, null=True)),
                ('detenido', models.CharField(max_length=5)),
                ('servicio_capturado', models.CharField(blank=True, max_length=500, null=True)),
                ('inicio_tecnico_lavado', models.DateTimeField(blank=True, null=True)),
                ('fin_tecnico_lavado', models.DateTimeField(blank=True, null=True)),
                ('ultima_actualizacion', models.IntegerField(blank=True, null=True)),
                ('motivo_paro', models.CharField(blank=True, max_length=22, null=True)),
                ('id_hd', models.CharField(max_length=25)),
                ('telefono_agencia', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'v_tracker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VCitasUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvegrupo', models.IntegerField(db_column='cveGrupo')),
                ('cveperfil', models.IntegerField(db_column='cvePerfil')),
                ('cveusuario', models.CharField(db_column='cveUsuario', max_length=15)),
                ('pass_field', models.CharField(db_column='Pass', max_length=100)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=150, null=True)),
                ('correoe', models.CharField(blank=True, db_column='correoE', max_length=100, null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=50, null=True)),
                ('cveasesor', models.CharField(blank=True, db_column='cveAsesor', max_length=20, null=True)),
            ],
            options={
                'db_table': 'v_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VInformacionCitas',
            fields=[
                ('id_hd', models.AutoField(primary_key=True, serialize=False)),
                ('no_cita', models.CharField(max_length=25)),
                ('no_orden', models.CharField(max_length=25)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('hora_retiro', models.DateTimeField(blank=True, null=True)),
                ('placas', models.CharField(blank=True, max_length=10, null=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('vehiculo', models.CharField(blank=True, max_length=250, null=True)),
                ('color', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'v_informacion_citas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadesCitas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no_cita', models.BigIntegerField()),
                ('id_tecnico', models.CharField(blank=True, max_length=50, null=True)),
                ('id_asesor', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cita', models.DateField()),
                ('no_placas', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=300)),
                ('correo', models.CharField(max_length=300)),
                ('modelo_vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('color_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo', models.IntegerField()),
                ('hora_rampa', models.TimeField()),
                ('year_vehiculo', models.IntegerField()),
                ('vin', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=50)),
                ('hora_cita', models.TimeField()),
                ('fecha_hora_fin', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_hora_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp', models.BooleanField(default=False)),
                ('kilometraje', models.BigIntegerField(blank=True, null=True)),
                ('id_hd', models.BigIntegerField(blank=True, null=True)),
                ('id_estado', models.BigIntegerField(blank=True, null=True)),
                ('comentario', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'actividades_citas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ActividadesCitasServicios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no_cita', models.BigIntegerField(blank=True, null=True)),
                ('id_servicio', models.BigIntegerField(blank=True, null=True)),
                ('servicio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'actividades_citas_servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CitasStatusCita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no_cita', models.BigIntegerField(blank=True, null=True)),
                ('fecha_hora_fin_cita', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_confirmacion_cita', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin_preinventario', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin_prediagnostico', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin_cancelacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'status_cita',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListaItemsFamiliasServicios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lista_items_familias_servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListaItemsModelos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lista_items_modelos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListaItemsServicios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_servicio', models.BigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('familia', models.BigIntegerField(blank=True, null=True)),
                ('orden', models.BigIntegerField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'lista_items_servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListaItemsYears',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'lista_items_years',
                'managed': True,
            },
        ),
    ]
