# Generated by Django 4.0.8 on 2023-01-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_dinissan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadescitas',
            options={'managed': True, 'verbose_name': 'cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='actividadescitasservicios',
            options={'managed': True, 'verbose_name': 'servicio solicitado', 'verbose_name_plural': 'Servicios solicitados'},
        ),
        migrations.AlterModelOptions(
            name='listaitemsfamiliasservicios',
            options={'managed': True, 'verbose_name': 'familia de servicios', 'verbose_name_plural': 'Familias de servicios'},
        ),
        migrations.AlterModelOptions(
            name='listaitemsmodelos',
            options={'managed': True, 'verbose_name': 'modelo de vehículo', 'verbose_name_plural': 'Modelos de vehículos'},
        ),
        migrations.AlterModelOptions(
            name='listaitemsservicios',
            options={'managed': True, 'verbose_name': 'servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='listaitemsyears',
            options={'managed': True, 'verbose_name': 'año de vehículo', 'verbose_name_plural': 'Años de vehículos'},
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='cliente',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='comentario',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='correo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='hora_cita',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='hora_rampa',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='no_cita',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='no_placas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='servicio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='tiempo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='vin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='whatsapp',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='actividadescitas',
            name='year_vehiculo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
