# Generated by Django 4.1.5 on 2023-01-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas_dinissan", "0002_alter_actividadescitas_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgenciaTablero",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("id_agencia", models.CharField(max_length=25)),
                ("nombre", models.CharField(max_length=300)),
                ("ciudad", models.CharField(max_length=300)),
                ("url_api_tablero", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "Agencia",
                "verbose_name_plural": "Agencias",
                "managed": True,
            },
        ),
    ]
