# Generated by Django 4.2.2 on 2023-12-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_dinissan', '0004_fallasintoma_motivoingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadescitas',
            name='id_agencia',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
