# Generated by Django 4.2.2 on 2024-04-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_dinissan', '0006_motivoingresomazda'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadescitas',
            name='no_cita_vardi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actividadescitas',
            name='observaciones',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
